
# Setup
title: Blue Dot Blog
tagline: '테스트'
description: '블로그 제작 중입니다. reinforce leaning, algorithm, robotics'
url: https://leechangyeol.github.io/
baseurl: ''


gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name:              Lee changyeol
  url:               https://leechangyeol.github.io/
  email:             wjwndml@gmail.com
  github_username: leechangyeol
#comments
comments:
    provider: "disqus"
    disqus:
        shortname: "leechangyeol-github-io"

# Custom vars
version:             1.0.0



